/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_clib4j_Matcher_Matcher */

#ifndef _Included_org_clib4j_Matcher_Matcher
#define _Included_org_clib4j_Matcher_Matcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    C_Constructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_clib4j_Matcher_Matcher_C_1Constructor
  (JNIEnv *, jclass);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    C_Destructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_clib4j_Matcher_Matcher_C_1Destructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    Append
 * Signature: (Ljava/lang/String;IIJ)V
 */
JNIEXPORT void JNICALL Java_org_clib4j_Matcher_Matcher_Append
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    DesAndAppend
 * Signature: (Ljava/lang/String;IIJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clib4j_Matcher_Matcher_DesAndAppend
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    Query
 * Signature: (Ljava/lang/String;IIJ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_clib4j_Matcher_Matcher_Query
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    QueryByPic
 * Signature: (Ljava/lang/String;IIJ)[I
 */
JNIEXPORT jintArray JNICALL Java_org_clib4j_Matcher_Matcher_QueryByPic
  (JNIEnv *, jclass, jstring, jint, jint, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    Remove
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_org_clib4j_Matcher_Matcher_Remove
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    getDes
 * Signature: (Ljava/lang/String;IJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_clib4j_Matcher_Matcher_getDes
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     org_clib4j_Matcher_Matcher
 * Method:    Size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_clib4j_Matcher_Matcher_Size
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
