/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_clib4j_communicator_communicator */

#ifndef _Included_org_clib4j_communicator_communicator
#define _Included_org_clib4j_communicator_communicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_clib4j_communicator_communicator
 * Method:    printnumber
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_clib4j_communicator_communicator_printnumber
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
